package com.accp.myoa.entity;

import java.util.HashSet;
import java.util.Set;

/**
 * BoardRoom generated by MyEclipse Persistence Tools
 */

public class BoardRoom implements java.io.Serializable {

	// Fields

	private Integer boardRoomId;
	private String boardRoomName;
	private Integer holdNumber;
	private String boardRoomRemark;
	private String boardRoomAddress;
	private Set meetings = new HashSet(0);

	// Constructors

	/** default constructor */
	public BoardRoom() {
	}

	/** minimal constructor */
	public BoardRoom(String boardRoomName, Integer holdNumber,
			String boardRoomAddress) {
		this.boardRoomName = boardRoomName;
		this.holdNumber = holdNumber;
		this.boardRoomAddress = boardRoomAddress;
	}

	/** full constructor */
	public BoardRoom(String boardRoomName, Integer holdNumber,
			String boardRoomRemark, String boardRoomAddress, Set meetings) {
		this.boardRoomName = boardRoomName;
		this.holdNumber = holdNumber;
		this.boardRoomRemark = boardRoomRemark;
		this.boardRoomAddress = boardRoomAddress;
		this.meetings = meetings;
	}

	// Property accessors

	public Integer getBoardRoomId() {
		return this.boardRoomId;
	}

	public void setBoardRoomId(Integer boardRoomId) {
		this.boardRoomId = boardRoomId;
	}

	public String getBoardRoomName() {
		return this.boardRoomName;
	}

	public void setBoardRoomName(String boardRoomName) {
		this.boardRoomName = boardRoomName;
	}

	public Integer getHoldNumber() {
		return this.holdNumber;
	}

	public void setHoldNumber(Integer holdNumber) {
		this.holdNumber = holdNumber;
	}

	public String getBoardRoomRemark() {
		return this.boardRoomRemark;
	}

	public void setBoardRoomRemark(String boardRoomRemark) {
		this.boardRoomRemark = boardRoomRemark;
	}

	public String getBoardRoomAddress() {
		return this.boardRoomAddress;
	}

	public void setBoardRoomAddress(String boardRoomAddress) {
		this.boardRoomAddress = boardRoomAddress;
	}

	public Set getMeetings() {
		return this.meetings;
	}

	public void setMeetings(Set meetings) {
		this.meetings = meetings;
	}

}