package com.accp.myoa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bulletin generated by MyEclipse Persistence Tools
 */

public class Bulletin implements java.io.Serializable {

	// Fields

	private Integer bulletinId;
	private ExamineState examineState;
	private User user;
	private String bulletinTitle;
	private String bulletinContent;
	private Date bulletinDate;
	private Integer available;
	private Set bulletinExamines = new HashSet(0);
	private Set bulletinReads = new HashSet(0);

	// Constructors

	/** default constructor */
	public Bulletin() {
		examineState=new ExamineState();
		user=new User();
	}

	/** minimal constructor */
	public Bulletin(ExamineState examineState, User user,
			String bulletinTitle, String bulletinContent, Date bulletinDate,
			Integer available) {
		this.examineState = examineState;
		this.user = user;
		this.bulletinTitle = bulletinTitle;
		this.bulletinContent = bulletinContent;
		this.bulletinDate = bulletinDate;
		this.available = available;
	}

	/** full constructor */
	public Bulletin(ExamineState examineState, User user,
			String bulletinTitle, String bulletinContent, Date bulletinDate,
			Integer available, Set bulletinExamines, Set bulletinReads) {
		this.examineState = examineState;
		this.user = user;
		this.bulletinTitle = bulletinTitle;
		this.bulletinContent = bulletinContent;
		this.bulletinDate = bulletinDate;
		this.available = available;
		this.bulletinExamines = bulletinExamines;
		this.bulletinReads = bulletinReads;
	}

	// Property accessors

	public Integer getBulletinId() {
		return this.bulletinId;
	}

	public void setBulletinId(Integer bulletinId) {
		this.bulletinId = bulletinId;
	}

	public ExamineState getExamineState() {
		return this.examineState;
	}

	public void setExamineState(ExamineState examineState) {
		this.examineState = examineState;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getBulletinTitle() {
		return this.bulletinTitle;
	}

	public void setBulletinTitle(String bulletinTitle) {
		this.bulletinTitle = bulletinTitle;
	}

	public String getBulletinContent() {
		return this.bulletinContent;
	}

	public void setBulletinContent(String bulletinContent) {
		this.bulletinContent = bulletinContent;
	}

	public Date getBulletinDate() {
		return this.bulletinDate;
	}

	public void setBulletinDate(Date bulletinDate) {
		this.bulletinDate = bulletinDate;
	}

	public Integer getAvailable() {
		return this.available;
	}

	public void setAvailable(Integer available) {
		this.available = available;
	}

	public Set getBulletinExamines() {
		return this.bulletinExamines;
	}

	public void setBulletinExamines(Set bulletinExamines) {
		this.bulletinExamines = bulletinExamines;
	}

	public Set getBulletinReads() {
		return this.bulletinReads;
	}

	public void setBulletinReads(Set bulletinReads) {
		this.bulletinReads = bulletinReads;
	}

}