package com.accp.myoa.entity;

/**
 * BulletinRead generated by MyEclipse Persistence Tools
 */

public class BulletinRead implements java.io.Serializable {

	// Fields

	private Integer bulletinReadId;
	private Bulletin bulletin;
	private ReadState readState;
	private User user;

	// Constructors

	/** default constructor */
	public BulletinRead() {
	}

	/** full constructor */
	public BulletinRead(Bulletin bulletin, ReadState readState, User user) {
		this.bulletin = bulletin;
		this.readState = readState;
		this.user = user;
	}

	// Property accessors

	public Integer getBulletinReadId() {
		return this.bulletinReadId;
	}

	public void setBulletinReadId(Integer bulletinReadId) {
		this.bulletinReadId = bulletinReadId;
	}

	public Bulletin getBulletin() {
		return this.bulletin;
	}

	public void setBulletin(Bulletin bulletin) {
		this.bulletin = bulletin;
	}

	public ReadState getReadState() {
		return this.readState;
	}

	public void setReadState(ReadState readState) {
		this.readState = readState;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}