package com.accp.myoa.entity;

/**
 * BulletinExamine generated by MyEclipse Persistence Tools
 */

public class BulletinExamine implements java.io.Serializable {

	// Fields

	private Integer bulletinExamineId;
	private Bulletin bulletin;
	private User user;

	// Constructors

	/** default constructor */
	public BulletinExamine() {
	}

	/** full constructor */
	public BulletinExamine(Bulletin bulletin, User user) {
		this.bulletin = bulletin;
		this.user = user;
	}

	// Property accessors

	public Integer getBulletinExamineId() {
		return this.bulletinExamineId;
	}

	public void setBulletinExamineId(Integer bulletinExamineId) {
		this.bulletinExamineId = bulletinExamineId;
	}

	public Bulletin getBulletin() {
		return this.bulletin;
	}

	public void setBulletin(Bulletin bulletin) {
		this.bulletin = bulletin;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}