package com.accp.myoa.entity;

import java.util.HashSet;
import java.util.Set;

/**
 * Car generated by MyEclipse Persistence Tools
 */

public class Car implements java.io.Serializable {

	// Fields

	private Integer carId;
	private String carNo;
	private Integer carState;
	private Set carApplies = new HashSet(0);

	// Constructors

	/** default constructor */
	public Car() {
	}

	/** minimal constructor */
	public Car(String carNo, Integer carState) {
		this.carNo = carNo;
		this.carState = carState;
	}

	/** full constructor */
	public Car(String carNo, Integer carState, Set carApplies) {
		this.carNo = carNo;
		this.carState = carState;
		this.carApplies = carApplies;
	}

	// Property accessors

	public Integer getCarId() {
		return this.carId;
	}

	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	public String getCarNo() {
		return this.carNo;
	}

	public void setCarNo(String carNo) {
		this.carNo = carNo;
	}

	public Integer getCarState() {
		return this.carState;
	}

	public void setCarState(Integer carState) {
		this.carState = carState;
	}

	public Set getCarApplies() {
		return this.carApplies;
	}

	public void setCarApplies(Set carApplies) {
		this.carApplies = carApplies;
	}

}