package com.accp.myoa.entity;

import java.util.Date;

/**
 * CarApply generated by MyEclipse Persistence Tools
 */

public class CarApply implements java.io.Serializable {

	// Fields

	private Integer carApplyId;
	private User userByDebuger;
	private User userByMotorMan;
	private User userByProposer;
	private Car car;
	private Date startDate;
	private Date endDate;
	private Date prepDate;
	private String startTerra;
	private String destination;
	private Integer examineStateId;
	private String mainContent;
	private String carApplyRemark;

	// Constructors

	/** default constructor */
	public CarApply() {
	}

	/** minimal constructor */
	public CarApply(User userByDebuger, User userByMotorMan,
			User userByProposer, Car car, Date startDate, Date endDate,
			Date prepDate, String startTerra, String destination,
			Integer examineStateId, String mainContent) {
		this.userByDebuger = userByDebuger;
		this.userByMotorMan = userByMotorMan;
		this.userByProposer = userByProposer;
		this.car = car;
		this.startDate = startDate;
		this.endDate = endDate;
		this.prepDate = prepDate;
		this.startTerra = startTerra;
		this.destination = destination;
		this.examineStateId = examineStateId;
		this.mainContent = mainContent;
	}

	/** full constructor */
	public CarApply(User userByDebuger, User userByMotorMan,
			User userByProposer, Car car, Date startDate, Date endDate,
			Date prepDate, String startTerra, String destination,
			Integer examineStateId, String mainContent, String carApplyRemark) {
		this.userByDebuger = userByDebuger;
		this.userByMotorMan = userByMotorMan;
		this.userByProposer = userByProposer;
		this.car = car;
		this.startDate = startDate;
		this.endDate = endDate;
		this.prepDate = prepDate;
		this.startTerra = startTerra;
		this.destination = destination;
		this.examineStateId = examineStateId;
		this.mainContent = mainContent;
		this.carApplyRemark = carApplyRemark;
	}

	// Property accessors

	public Integer getCarApplyId() {
		return this.carApplyId;
	}

	public void setCarApplyId(Integer carApplyId) {
		this.carApplyId = carApplyId;
	}

	public User getUserByDebuger() {
		return this.userByDebuger;
	}

	public void setUserByDebuger(User userByDebuger) {
		this.userByDebuger = userByDebuger;
	}

	public User getUserByMotorMan() {
		return this.userByMotorMan;
	}

	public void setUserByMotorMan(User userByMotorMan) {
		this.userByMotorMan = userByMotorMan;
	}

	public User getUserByProposer() {
		return this.userByProposer;
	}

	public void setUserByProposer(User userByProposer) {
		this.userByProposer = userByProposer;
	}

	public Car getCar() {
		return this.car;
	}

	public void setCar(Car car) {
		this.car = car;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Date getPrepDate() {
		return this.prepDate;
	}

	public void setPrepDate(Date prepDate) {
		this.prepDate = prepDate;
	}

	public String getStartTerra() {
		return this.startTerra;
	}

	public void setStartTerra(String startTerra) {
		this.startTerra = startTerra;
	}

	public String getDestination() {
		return this.destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	public Integer getExamineStateId() {
		return this.examineStateId;
	}

	public void setExamineStateId(Integer examineStateId) {
		this.examineStateId = examineStateId;
	}

	public String getMainContent() {
		return this.mainContent;
	}

	public void setMainContent(String mainContent) {
		this.mainContent = mainContent;
	}

	public String getCarApplyRemark() {
		return this.carApplyRemark;
	}

	public void setCarApplyRemark(String carApplyRemark) {
		this.carApplyRemark = carApplyRemark;
	}

}