package com.accp.myoa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by MyEclipse Persistence Tools
 */

public class Client implements java.io.Serializable {

	// Fields

	private Integer clientId;
	private String clientName;
	private Date birthday;
	private String address;
	private String mobilePhone;
	private String qq;
	private String fax;
	private String email;
	private String position;
	private Integer sex;
	private String clientRemark;
	private Set clientCompanies = new HashSet(0);

	// Constructors

	/** default constructor */
	public Client() {
	}

	/** minimal constructor */
	public Client(String clientName, Integer sex) {
		this.clientName = clientName;
		this.sex = sex;
	}

	/** full constructor */
	public Client(String clientName, Date birthday, String address,
			String mobilePhone, String qq, String fax, String email,
			String position, Integer sex, String clientRemark,
			Set clientCompanies) {
		this.clientName = clientName;
		this.birthday = birthday;
		this.address = address;
		this.mobilePhone = mobilePhone;
		this.qq = qq;
		this.fax = fax;
		this.email = email;
		this.position = position;
		this.sex = sex;
		this.clientRemark = clientRemark;
		this.clientCompanies = clientCompanies;
	}

	// Property accessors

	public Integer getClientId() {
		return this.clientId;
	}

	public void setClientId(Integer clientId) {
		this.clientId = clientId;
	}

	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getMobilePhone() {
		return this.mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	public String getClientRemark() {
		return this.clientRemark;
	}

	public void setClientRemark(String clientRemark) {
		this.clientRemark = clientRemark;
	}

	public Set getClientCompanies() {
		return this.clientCompanies;
	}

	public void setClientCompanies(Set clientCompanies) {
		this.clientCompanies = clientCompanies;
	}

}