package com.accp.myoa.entity;

import java.util.HashSet;
import java.util.Set;

/**
 * ComleteDegress generated by MyEclipse Persistence Tools
 */

public class ComleteDegress implements java.io.Serializable {

	// Fields

	private Integer comleteDegressId;
	private String comleteDegressName;
	private String comleteDegressRemark;
	private Set weekDiaries = new HashSet(0);
	private Set diaries = new HashSet(0);

	// Constructors

	/** default constructor */
	public ComleteDegress() {
	}

	/** minimal constructor */
	public ComleteDegress(String comleteDegressName) {
		this.comleteDegressName = comleteDegressName;
	}

	/** full constructor */
	public ComleteDegress(String comleteDegressName,
			String comleteDegressRemark, Set weekDiaries, Set diaries) {
		this.comleteDegressName = comleteDegressName;
		this.comleteDegressRemark = comleteDegressRemark;
		this.weekDiaries = weekDiaries;
		this.diaries = diaries;
	}

	// Property accessors

	public Integer getComleteDegressId() {
		return this.comleteDegressId;
	}

	public void setComleteDegressId(Integer comleteDegressId) {
		this.comleteDegressId = comleteDegressId;
	}

	public String getComleteDegressName() {
		return this.comleteDegressName;
	}

	public void setComleteDegressName(String comleteDegressName) {
		this.comleteDegressName = comleteDegressName;
	}

	public String getComleteDegressRemark() {
		return this.comleteDegressRemark;
	}

	public void setComleteDegressRemark(String comleteDegressRemark) {
		this.comleteDegressRemark = comleteDegressRemark;
	}

	public Set getWeekDiaries() {
		return this.weekDiaries;
	}

	public void setWeekDiaries(Set weekDiaries) {
		this.weekDiaries = weekDiaries;
	}

	public Set getDiaries() {
		return this.diaries;
	}

	public void setDiaries(Set diaries) {
		this.diaries = diaries;
	}

}