package com.accp.myoa.entity;

import java.util.HashSet;
import java.util.Set;

/**
 * DeptPosition generated by MyEclipse Persistence Tools
 */

public class DeptPosition implements java.io.Serializable {

	// Fields

	private Integer deptPositionId;
	private Position position;
	private Dept dept;
	private String deptPositionRemark;
	//private Set positionPopedoms = new HashSet(0);
	//private Set users = new HashSet(0);

	// Constructors

	/** default constructor */
	public DeptPosition() {
	}

	/** minimal constructor */
	public DeptPosition(Position position, Dept dept) {
		this.position = position;
		this.dept = dept;
	}

	/** full constructor */
	public DeptPosition(Position position, Dept dept,
			String deptPositionRemark) {
		this.position = position;
		this.dept = dept;
		this.deptPositionRemark = deptPositionRemark;
		//this.positionPopedoms = positionPopedoms;
		//this.users = users;
	}

	// Property accessors

	public Integer getDeptPositionId() {
		return this.deptPositionId;
	}

	public void setDeptPositionId(Integer deptPositionId) {
		this.deptPositionId = deptPositionId;
	}

	public Position getPosition() {
		return this.position;
	}

	public void setPosition(Position position) {
		this.position = position;
	}

	public Dept getDept() {
		return this.dept;
	}

	public void setDept(Dept dept) {
		this.dept = dept;
	}

	public String getDeptPositionRemark() {
		return this.deptPositionRemark;
	}

	public void setDeptPositionRemark(String deptPositionRemark) {
		this.deptPositionRemark = deptPositionRemark;
	}

//	public Set getPositionPopedoms() {
//		return this.positionPopedoms;
//	}
//
//	public void setPositionPopedoms(Set positionPopedoms) {
//		this.positionPopedoms = positionPopedoms;
//	}
//
//	public Set getUsers() {
//		return this.users;
//	}
//
//	public void setUsers(Set users) {
//		this.users = users;
//	}

}