package com.accp.myoa.entity;

import java.util.HashSet;
import java.util.Set;

/**
 * Dept generated by MyEclipse Persistence Tools
 */

public class Dept implements java.io.Serializable {

	// Fields

	private Integer deptId;
	private String deptName;
	private String deptPhone;
	private String deptFax;
	private String deptRemark;
	//private Set deptPositions = new HashSet(0);

	// Constructors

	/** default constructor */
	public Dept() {
	}

	/** minimal constructor */
	public Dept(String deptName) {
		this.deptName = deptName;
	}

	/** full constructor */
	public Dept(String deptName, String deptPhone, String deptFax,
			String deptRemark) {
		this.deptName = deptName;
		this.deptPhone = deptPhone;
		this.deptFax = deptFax;
		this.deptRemark = deptRemark;
		
	}

	// Property accessors

	public Integer getDeptId() {
		return this.deptId;
	}

	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getDeptPhone() {
		return this.deptPhone;
	}

	public void setDeptPhone(String deptPhone) {
		this.deptPhone = deptPhone;
	}

	public String getDeptFax() {
		return this.deptFax;
	}

	public void setDeptFax(String deptFax) {
		this.deptFax = deptFax;
	}

	public String getDeptRemark() {
		return this.deptRemark;
	}

	public void setDeptRemark(String deptRemark) {
		this.deptRemark = deptRemark;
	}

//	public Set getDeptPositions() {
//		return this.deptPositions;
//	}
//
//	public void setDeptPositions(Set deptPositions) {
//		this.deptPositions = deptPositions;
//	}

}