package com.accp.myoa.entity;

import java.util.Date;

/**
 * Diary generated by MyEclipse Persistence Tools
 */

public class Diary implements java.io.Serializable {

	// Fields

	private Integer diaryId;
	private ComleteDegress comleteDegress;
	private User user;
	private String diaryTitle;
	private String diaryContent;
	private Date diaryDate;

	// Constructors

	/** default constructor */
	public Diary() {
	}

	/** full constructor */
	public Diary(ComleteDegress comleteDegress, User user, String diaryTitle,
			String diaryContent, Date diaryDate) {
		this.comleteDegress = comleteDegress;
		this.user = user;
		this.diaryTitle = diaryTitle;
		this.diaryContent = diaryContent;
		this.diaryDate = diaryDate;
	}

	// Property accessors

	public Integer getDiaryId() {
		return this.diaryId;
	}

	public void setDiaryId(Integer diaryId) {
		this.diaryId = diaryId;
	}

	public ComleteDegress getComleteDegress() {
		return this.comleteDegress;
	}

	public void setComleteDegress(ComleteDegress comleteDegress) {
		this.comleteDegress = comleteDegress;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getDiaryTitle() {
		return this.diaryTitle;
	}

	public void setDiaryTitle(String diaryTitle) {
		this.diaryTitle = diaryTitle;
	}

	public String getDiaryContent() {
		return this.diaryContent;
	}

	public void setDiaryContent(String diaryContent) {
		this.diaryContent = diaryContent;
	}

	public Date getDiaryDate() {
		return this.diaryDate;
	}

	public void setDiaryDate(Date diaryDate) {
		this.diaryDate = diaryDate;
	}

}