package com.accp.myoa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Document generated by MyEclipse Persistence Tools
 */

public class Document implements java.io.Serializable {

	// Fields

	private Integer documentId;
	private ExamineState examineState;
	private User user;
	private String documentTitle;
	private String documentContent;
	private Date documentDate;
	private Set documentExamines = new HashSet(0);

	// Constructors

	/** default constructor */
	public Document() {
	}

	/** minimal constructor */
	public Document(ExamineState examineState, User user, String documentTitle,
			String documentContent, Date documentDate) {
		this.examineState = examineState;
		this.user = user;
		this.documentTitle = documentTitle;
		this.documentContent = documentContent;
		this.documentDate = documentDate;
	}

	/** full constructor */
	public Document(ExamineState examineState, User user, String documentTitle,
			String documentContent, Date documentDate, Set documentExamines) {
		this.examineState = examineState;
		this.user = user;
		this.documentTitle = documentTitle;
		this.documentContent = documentContent;
		this.documentDate = documentDate;
		this.documentExamines = documentExamines;
	}

	// Property accessors

	public Integer getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(Integer documentId) {
		this.documentId = documentId;
	}

	public ExamineState getExamineState() {
		return this.examineState;
	}

	public void setExamineState(ExamineState examineState) {
		this.examineState = examineState;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getDocumentTitle() {
		return this.documentTitle;
	}

	public void setDocumentTitle(String documentTitle) {
		this.documentTitle = documentTitle;
	}

	public String getDocumentContent() {
		return this.documentContent;
	}

	public void setDocumentContent(String documentContent) {
		this.documentContent = documentContent;
	}

	public Date getDocumentDate() {
		return this.documentDate;
	}

	public void setDocumentDate(Date documentDate) {
		this.documentDate = documentDate;
	}

	public Set getDocumentExamines() {
		return this.documentExamines;
	}

	public void setDocumentExamines(Set documentExamines) {
		this.documentExamines = documentExamines;
	}

}