package com.accp.myoa.entity;

/**
 * DocumentExamine generated by MyEclipse Persistence Tools
 */

public class DocumentExamine implements java.io.Serializable {

	// Fields

	private Integer documentExamineId;
	private Document document;
	private User user;

	// Constructors

	/** default constructor */
	public DocumentExamine() {
	}

	/** full constructor */
	public DocumentExamine(Document document, User user) {
		this.document = document;
		this.user = user;
	}

	// Property accessors

	public Integer getDocumentExamineId() {
		return this.documentExamineId;
	}

	public void setDocumentExamineId(Integer documentExamineId) {
		this.documentExamineId = documentExamineId;
	}

	public Document getDocument() {
		return this.document;
	}

	public void setDocument(Document document) {
		this.document = document;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}