package com.accp.myoa.entity;

/**
 * DocumentRead generated by MyEclipse Persistence Tools
 */

public class DocumentRead implements java.io.Serializable {

	// Fields

	private Integer documentReadId;
	private ReadState readState;
	private User user;
	private Integer documentId;

	// Constructors

	/** default constructor */
	public DocumentRead() {
	}

	/** full constructor */
	public DocumentRead(ReadState readState, User user, Integer documentId) {
		this.readState = readState;
		this.user = user;
		this.documentId = documentId;
	}

	// Property accessors

	public Integer getDocumentReadId() {
		return this.documentReadId;
	}

	public void setDocumentReadId(Integer documentReadId) {
		this.documentReadId = documentReadId;
	}

	public ReadState getReadState() {
		return this.readState;
	}

	public void setReadState(ReadState readState) {
		this.readState = readState;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Integer getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(Integer documentId) {
		this.documentId = documentId;
	}

}