package com.accp.myoa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Egress generated by MyEclipse Persistence Tools
 */

public class Egress implements java.io.Serializable {

	// Fields

	private Integer egressId;
	private User user;
	private String egressTitle;
	private String egerssContent;
	private Date startDate;
	private Date prepDate;
	private Date endDate;
	private String egressRemark;
	private Set egressExamines = new HashSet(0);

	// Constructors

	/** default constructor */
	public Egress() {
	}

	/** minimal constructor */
	public Egress(User user, String egressTitle, String egerssContent,
			Date startDate, Date prepDate, Date endDate, String egressRemark) {
		this.user = user;
		this.egressTitle = egressTitle;
		this.egerssContent = egerssContent;
		this.startDate = startDate;
		this.prepDate = prepDate;
		this.endDate = endDate;
		this.egressRemark = egressRemark;
	}

	/** full constructor */
	public Egress(User user, String egressTitle, String egerssContent,
			Date startDate, Date prepDate, Date endDate, String egressRemark,
			Set egressExamines) {
		this.user = user;
		this.egressTitle = egressTitle;
		this.egerssContent = egerssContent;
		this.startDate = startDate;
		this.prepDate = prepDate;
		this.endDate = endDate;
		this.egressRemark = egressRemark;
		this.egressExamines = egressExamines;
	}

	// Property accessors

	public Integer getEgressId() {
		return this.egressId;
	}

	public void setEgressId(Integer egressId) {
		this.egressId = egressId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getEgressTitle() {
		return this.egressTitle;
	}

	public void setEgressTitle(String egressTitle) {
		this.egressTitle = egressTitle;
	}

	public String getEgerssContent() {
		return this.egerssContent;
	}

	public void setEgerssContent(String egerssContent) {
		this.egerssContent = egerssContent;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getPrepDate() {
		return this.prepDate;
	}

	public void setPrepDate(Date prepDate) {
		this.prepDate = prepDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getEgressRemark() {
		return this.egressRemark;
	}

	public void setEgressRemark(String egressRemark) {
		this.egressRemark = egressRemark;
	}

	public Set getEgressExamines() {
		return this.egressExamines;
	}

	public void setEgressExamines(Set egressExamines) {
		this.egressExamines = egressExamines;
	}

}