package com.accp.myoa.entity;

/**
 * EgressExamine generated by MyEclipse Persistence Tools
 */

public class EgressExamine implements java.io.Serializable {

	// Fields

	private Integer egressExamineId;
	private Egress egress;
	private User user;
	private Integer egressState;

	// Constructors

	/** default constructor */
	public EgressExamine() {
	}

	/** full constructor */
	public EgressExamine(Egress egress, User user, Integer egressState) {
		this.egress = egress;
		this.user = user;
		this.egressState = egressState;
	}

	// Property accessors

	public Integer getEgressExamineId() {
		return this.egressExamineId;
	}

	public void setEgressExamineId(Integer egressExamineId) {
		this.egressExamineId = egressExamineId;
	}

	public Egress getEgress() {
		return this.egress;
	}

	public void setEgress(Egress egress) {
		this.egress = egress;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Integer getEgressState() {
		return this.egressState;
	}

	public void setEgressState(Integer egressState) {
		this.egressState = egressState;
	}

}