package com.accp.myoa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Email generated by MyEclipse Persistence Tools
 */

public class Email implements java.io.Serializable {

	// Fields

	private Integer emailId;
	private EmailType emailType=new EmailType();
	private User user=new User();
	private String emailTitle;
	private String emailContent;
	private Date emailDate;
	//private Set files = new HashSet(0);
	//private Set emailReceivces = new HashSet(0);

	// Constructors

	/** default constructor */
	public Email() {
	}

	/** minimal constructor */
	public Email(EmailType emailType, User user, String emailTitle,
			String emailContent, Date emailDate) {
		this.emailType = emailType;
		this.user = user;
		this.emailTitle = emailTitle;
		this.emailContent = emailContent;
		this.emailDate = emailDate;
	}

	
	

	// Property accessors

	public Integer getEmailId() {
		return this.emailId;
	}

	public void setEmailId(Integer emailId) {
		this.emailId = emailId;
	}

	public EmailType getEmailType() {
		return this.emailType;
	}

	public void setEmailType(EmailType emailType) {
		this.emailType = emailType;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getEmailTitle() {
		return this.emailTitle;
	}

	public void setEmailTitle(String emailTitle) {
		this.emailTitle = emailTitle;
	}

	public String getEmailContent() {
		return this.emailContent;
	}

	public void setEmailContent(String emailContent) {
		this.emailContent = emailContent;
	}

	public Date getEmailDate() {
		return this.emailDate;
	}

	public void setEmailDate(Date emailDate) {
		this.emailDate = emailDate;
	}



}