package com.accp.myoa.entity;

import java.util.HashSet;
import java.util.Set;

/**
 * EmailType generated by MyEclipse Persistence Tools
 */

public class EmailType implements java.io.Serializable {

	// Fields

	private Integer emailTypeId;
	private String emailTypeName;
	private String emailTypeRemark;
	//private Set emails = new HashSet(0);

	// Constructors

	/** default constructor */
	public EmailType() {
	}

	/** minimal constructor */
	public EmailType(String emailTypeName) {
		this.emailTypeName = emailTypeName;
	}

	/** full constructor */
	public EmailType(String emailTypeName, String emailTypeRemark) {
		this.emailTypeName = emailTypeName;
		this.emailTypeRemark = emailTypeRemark;
	
	}

	// Property accessors

	public Integer getEmailTypeId() {
		return this.emailTypeId;
	}

	public void setEmailTypeId(Integer emailTypeId) {
		this.emailTypeId = emailTypeId;
	}

	public String getEmailTypeName() {
		return this.emailTypeName;
	}

	public void setEmailTypeName(String emailTypeName) {
		this.emailTypeName = emailTypeName;
	}

	public String getEmailTypeRemark() {
		return this.emailTypeRemark;
	}

	public void setEmailTypeRemark(String emailTypeRemark) {
		this.emailTypeRemark = emailTypeRemark;
	}



}