package com.accp.myoa.entity;

import java.util.HashSet;
import java.util.Set;

/**
 * ExamineState generated by MyEclipse Persistence Tools
 */

public class ExamineState implements java.io.Serializable {

	// Fields

	private Integer examineStateId;
	private String examineStateName;
	private String examineStateRemark;
	private Set meetings = new HashSet(0);
	private Set documents = new HashSet(0);

	// Constructors

	/** default constructor */
	public ExamineState() {
	}

	/** minimal constructor */
	public ExamineState(String examineStateName) {
		this.examineStateName = examineStateName;
	}

	/** full constructor */
	public ExamineState(String examineStateName, String examineStateRemark,
			Set meetings, Set documents) {
		this.examineStateName = examineStateName;
		this.examineStateRemark = examineStateRemark;
		this.meetings = meetings;
		this.documents = documents;
	}

	// Property accessors

	public Integer getExamineStateId() {
		return this.examineStateId;
	}

	public void setExamineStateId(Integer examineStateId) {
		this.examineStateId = examineStateId;
	}

	public String getExamineStateName() {
		return this.examineStateName;
	}

	public void setExamineStateName(String examineStateName) {
		this.examineStateName = examineStateName;
	}

	public String getExamineStateRemark() {
		return this.examineStateRemark;
	}

	public void setExamineStateRemark(String examineStateRemark) {
		this.examineStateRemark = examineStateRemark;
	}

	public Set getMeetings() {
		return this.meetings;
	}

	public void setMeetings(Set meetings) {
		this.meetings = meetings;
	}

	public Set getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set documents) {
		this.documents = documents;
	}

}