package com.accp.myoa.entity;

import java.util.Date;

/**
 * File generated by MyEclipse Persistence Tools
 */

public class File implements java.io.Serializable {

	// Fields

	private Integer fileId;
	private Email email;
	private User user;
	private String fileName;
	private Date uploadTime;
	private Integer fileState;

	// Constructors

	/** default constructor */
	public File() {
	}

	/** full constructor */
	public File(Email email, User user, String fileName, Date uploadTime,
			Integer fileState) {
		this.email = email;
		this.user = user;
		this.fileName = fileName;
		this.uploadTime = uploadTime;
		this.fileState = fileState;
	}

	// Property accessors

	public Integer getFileId() {
		return this.fileId;
	}

	public void setFileId(Integer fileId) {
		this.fileId = fileId;
	}

	public Email getEmail() {
		return this.email;
	}

	public void setEmail(Email email) {
		this.email = email;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public Date getUploadTime() {
		return this.uploadTime;
	}

	public void setUploadTime(Date uploadTime) {
		this.uploadTime = uploadTime;
	}

	public Integer getFileState() {
		return this.fileState;
	}

	public void setFileState(Integer fileState) {
		this.fileState = fileState;
	}

}