package com.accp.myoa.entity;

import java.util.Date;

/**
 * LeaveWord generated by MyEclipse Persistence Tools
 */

public class LeaveWord implements java.io.Serializable {

	// Fields

	private Integer leaveWordId;
	private User user;
	private String leaveWordContent;
	private Date leaveWordDate;

	// Constructors

	/** default constructor */
	public LeaveWord() {
	}

	/** full constructor */
	public LeaveWord(User user, String leaveWordContent, Date leaveWordDate) {
		this.user = user;
		this.leaveWordContent = leaveWordContent;
		this.leaveWordDate = leaveWordDate;
	}

	// Property accessors

	public Integer getLeaveWordId() {
		return this.leaveWordId;
	}

	public void setLeaveWordId(Integer leaveWordId) {
		this.leaveWordId = leaveWordId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getLeaveWordContent() {
		return this.leaveWordContent;
	}

	public void setLeaveWordContent(String leaveWordContent) {
		this.leaveWordContent = leaveWordContent;
	}

	public Date getLeaveWordDate() {
		return this.leaveWordDate;
	}

	public void setLeaveWordDate(Date leaveWordDate) {
		this.leaveWordDate = leaveWordDate;
	}

}