package com.accp.myoa.entity;

import java.util.HashSet;
import java.util.Set;

/**
 * Level generated by MyEclipse Persistence Tools
 */

public class Level implements java.io.Serializable {

	// Fields

	private Integer levelId;
	private String levelName;
	private String levelRemark;
	private Set scratchpads = new HashSet(0);

	// Constructors

	/** default constructor */
	public Level() {
	}

	/** minimal constructor */
	public Level(String levelName) {
		this.levelName = levelName;
	}

	/** full constructor */
	public Level(String levelName, String levelRemark, Set scratchpads) {
		this.levelName = levelName;
		this.levelRemark = levelRemark;
		this.scratchpads = scratchpads;
	}

	// Property accessors

	public Integer getLevelId() {
		return this.levelId;
	}

	public void setLevelId(Integer levelId) {
		this.levelId = levelId;
	}

	public String getLevelName() {
		return this.levelName;
	}

	public void setLevelName(String levelName) {
		this.levelName = levelName;
	}

	public String getLevelRemark() {
		return this.levelRemark;
	}

	public void setLevelRemark(String levelRemark) {
		this.levelRemark = levelRemark;
	}

	public Set getScratchpads() {
		return this.scratchpads;
	}

	public void setScratchpads(Set scratchpads) {
		this.scratchpads = scratchpads;
	}

}