package com.accp.myoa.entity;

import java.util.HashSet;
import java.util.Set;

/**
 * Meetingstate generated by MyEclipse Persistence Tools
 */

public class Meetingstate implements java.io.Serializable {

	// Fields

	private Integer meetingStateId;
	private String meetingStateName;
	private String meetingStateRemark;
	private Set meetings = new HashSet(0);

	// Constructors

	/** default constructor */
	public Meetingstate() {
	}

	/** minimal constructor */
	public Meetingstate(String meetingStateName) {
		this.meetingStateName = meetingStateName;
	}

	/** full constructor */
	public Meetingstate(String meetingStateName, String meetingStateRemark,
			Set meetings) {
		this.meetingStateName = meetingStateName;
		this.meetingStateRemark = meetingStateRemark;
		this.meetings = meetings;
	}

	// Property accessors

	public Integer getMeetingStateId() {
		return this.meetingStateId;
	}

	public void setMeetingStateId(Integer meetingStateId) {
		this.meetingStateId = meetingStateId;
	}

	public String getMeetingStateName() {
		return this.meetingStateName;
	}

	public void setMeetingStateName(String meetingStateName) {
		this.meetingStateName = meetingStateName;
	}

	public String getMeetingStateRemark() {
		return this.meetingStateRemark;
	}

	public void setMeetingStateRemark(String meetingStateRemark) {
		this.meetingStateRemark = meetingStateRemark;
	}

	public Set getMeetings() {
		return this.meetings;
	}

	public void setMeetings(Set meetings) {
		this.meetings = meetings;
	}

}