package com.accp.myoa.entity;

/**
 * MeetingRead generated by MyEclipse Persistence Tools
 */

public class MeetingRead implements java.io.Serializable {

	// Fields

	private Integer meetingReadId;
	private Meeting meeting;
	private ReadState readState;
	private User user;

	// Constructors

	/** default constructor */
	public MeetingRead() {
	}

	/** full constructor */
	public MeetingRead(Meeting meeting, ReadState readState, User user) {
		this.meeting = meeting;
		this.readState = readState;
		this.user = user;
	}

	// Property accessors

	public Integer getMeetingReadId() {
		return this.meetingReadId;
	}

	public void setMeetingReadId(Integer meetingReadId) {
		this.meetingReadId = meetingReadId;
	}

	public Meeting getMeeting() {
		return this.meeting;
	}

	public void setMeeting(Meeting meeting) {
		this.meeting = meeting;
	}

	public ReadState getReadState() {
		return this.readState;
	}

	public void setReadState(ReadState readState) {
		this.readState = readState;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}