package com.accp.myoa.entity;

/**
 * MeetingSummaryScan generated by MyEclipse Persistence Tools
 */

public class MeetingSummaryScan implements java.io.Serializable {

	// Fields

	private Integer meetingSummaryScanId;
	private User user;
	private Integer meetingSummaryId;

	// Constructors

	/** default constructor */
	public MeetingSummaryScan() {
	}

	/** full constructor */
	public MeetingSummaryScan(User user, Integer meetingSummaryId) {
		this.user = user;
		this.meetingSummaryId = meetingSummaryId;
	}

	// Property accessors

	public Integer getMeetingSummaryScanId() {
		return this.meetingSummaryScanId;
	}

	public void setMeetingSummaryScanId(Integer meetingSummaryScanId) {
		this.meetingSummaryScanId = meetingSummaryScanId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Integer getMeetingSummaryId() {
		return this.meetingSummaryId;
	}

	public void setMeetingSummaryId(Integer meetingSummaryId) {
		this.meetingSummaryId = meetingSummaryId;
	}

}