package com.accp.myoa.entity;

/**
 * MeetingSummary generated by MyEclipse Persistence Tools
 */

public class MeetingSummary implements java.io.Serializable {

	// Fields

	private Integer meetingSummaryId;
	private Meeting meeting;
	private String meetingSummaryContent;

	// Constructors

	/** default constructor */
	public MeetingSummary() {
	}

	/** full constructor */
	public MeetingSummary(Meeting meeting, String meetingSummaryContent) {
		this.meeting = meeting;
		this.meetingSummaryContent = meetingSummaryContent;
	}

	// Property accessors

	public Integer getMeetingSummaryId() {
		return this.meetingSummaryId;
	}

	public void setMeetingSummaryId(Integer meetingSummaryId) {
		this.meetingSummaryId = meetingSummaryId;
	}

	public Meeting getMeeting() {
		return this.meeting;
	}

	public void setMeeting(Meeting meeting) {
		this.meeting = meeting;
	}

	public String getMeetingSummaryContent() {
		return this.meetingSummaryContent;
	}

	public void setMeetingSummaryContent(String meetingSummaryContent) {
		this.meetingSummaryContent = meetingSummaryContent;
	}

}