package com.accp.myoa.entity;

import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by MyEclipse Persistence Tools
 */

public class Menu implements java.io.Serializable {

	// Fields

	private Integer menuId;
	private String menuName;
	private Integer menuParentId;
	private String menuPic;
	private Integer menuLevel;
	private String menuUrl;
	private String menuRemark;
	private Set positionPopedoms = new HashSet(0);

	// Constructors

	/** default constructor */
	public Menu() {
	}

	/** minimal constructor */
	public Menu(String menuName, Integer menuParentId, String menuPic,
			Integer menuLevel, String menuUrl) {
		this.menuName = menuName;
		this.menuParentId = menuParentId;
		this.menuPic = menuPic;
		this.menuLevel = menuLevel;
		this.menuUrl = menuUrl;
	}

	/** full constructor */
	public Menu(String menuName, Integer menuParentId, String menuPic,
			Integer menuLevel, String menuUrl, String menuRemark,
			Set positionPopedoms) {
		this.menuName = menuName;
		this.menuParentId = menuParentId;
		this.menuPic = menuPic;
		this.menuLevel = menuLevel;
		this.menuUrl = menuUrl;
		this.menuRemark = menuRemark;
		this.positionPopedoms = positionPopedoms;
	}

	// Property accessors

	public Integer getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	public Integer getMenuParentId() {
		return this.menuParentId;
	}

	public void setMenuParentId(Integer menuParentId) {
		this.menuParentId = menuParentId;
	}

	public String getMenuPic() {
		return this.menuPic;
	}

	public void setMenuPic(String menuPic) {
		this.menuPic = menuPic;
	}

	public Integer getMenuLevel() {
		return this.menuLevel;
	}

	public void setMenuLevel(Integer menuLevel) {
		this.menuLevel = menuLevel;
	}

	public String getMenuUrl() {
		return this.menuUrl;
	}

	public void setMenuUrl(String menuUrl) {
		this.menuUrl = menuUrl;
	}

	public String getMenuRemark() {
		return this.menuRemark;
	}

	public void setMenuRemark(String menuRemark) {
		this.menuRemark = menuRemark;
	}

	public Set getPositionPopedoms() {
		return this.positionPopedoms;
	}

	public void setPositionPopedoms(Set positionPopedoms) {
		this.positionPopedoms = positionPopedoms;
	}

}