package com.accp.myoa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Message generated by MyEclipse Persistence Tools
 */

public class Message implements java.io.Serializable {

	// Fields

	private Integer messageId;
	private MessageType messageType;
	private User user;
	private String messageContent;
	private Date messageDate;
	private Set messageReceives = new HashSet(0);

	// Constructors

	/** default constructor */
	public Message() {
	}

	/** minimal constructor */
	public Message(MessageType messageType, User user, String messageContent,
			Date messageDate) {
		this.messageType = messageType;
		this.user = user;
		this.messageContent = messageContent;
		this.messageDate = messageDate;
	}

	/** full constructor */
	public Message(MessageType messageType, User user, String messageContent,
			Date messageDate, Set messageReceives) {
		this.messageType = messageType;
		this.user = user;
		this.messageContent = messageContent;
		this.messageDate = messageDate;
		this.messageReceives = messageReceives;
	}

	// Property accessors

	public Integer getMessageId() {
		return this.messageId;
	}

	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	public MessageType getMessageType() {
		return this.messageType;
	}

	public void setMessageType(MessageType messageType) {
		this.messageType = messageType;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getMessageContent() {
		return this.messageContent;
	}

	public void setMessageContent(String messageContent) {
		this.messageContent = messageContent;
	}

	public Date getMessageDate() {
		return this.messageDate;
	}

	public void setMessageDate(Date messageDate) {
		this.messageDate = messageDate;
	}

	public Set getMessageReceives() {
		return this.messageReceives;
	}

	public void setMessageReceives(Set messageReceives) {
		this.messageReceives = messageReceives;
	}

}