package com.accp.myoa.entity;

import java.util.HashSet;
import java.util.Set;

/**
 * MessageType generated by MyEclipse Persistence Tools
 */

public class MessageType implements java.io.Serializable {

	// Fields

	private Integer messageTypeId;
	private String messageTypeName;
	private String messageTypePic;
	private Set messages = new HashSet(0);

	// Constructors

	/** default constructor */
	public MessageType() {
	}

	/** minimal constructor */
	public MessageType(String messageTypeName, String messageTypePic) {
		this.messageTypeName = messageTypeName;
		this.messageTypePic = messageTypePic;
	}

	/** full constructor */
	public MessageType(String messageTypeName, String messageTypePic,
			Set messages) {
		this.messageTypeName = messageTypeName;
		this.messageTypePic = messageTypePic;
		this.messages = messages;
	}

	// Property accessors

	public Integer getMessageTypeId() {
		return this.messageTypeId;
	}

	public void setMessageTypeId(Integer messageTypeId) {
		this.messageTypeId = messageTypeId;
	}

	public String getMessageTypeName() {
		return this.messageTypeName;
	}

	public void setMessageTypeName(String messageTypeName) {
		this.messageTypeName = messageTypeName;
	}

	public String getMessageTypePic() {
		return this.messageTypePic;
	}

	public void setMessageTypePic(String messageTypePic) {
		this.messageTypePic = messageTypePic;
	}

	public Set getMessages() {
		return this.messages;
	}

	public void setMessages(Set messages) {
		this.messages = messages;
	}

}