package com.accp.myoa.entity;

/**
 * MessageReceive generated by MyEclipse Persistence Tools
 */

public class MessageReceive implements java.io.Serializable {

	// Fields

	private Integer messageReceiveId;
	private Message message;
	private User user;

	// Constructors

	/** default constructor */
	public MessageReceive() {
	}

	/** full constructor */
	public MessageReceive(Message message, User user) {
		this.message = message;
		this.user = user;
	}

	// Property accessors

	public Integer getMessageReceiveId() {
		return this.messageReceiveId;
	}

	public void setMessageReceiveId(Integer messageReceiveId) {
		this.messageReceiveId = messageReceiveId;
	}

	public Message getMessage() {
		return this.message;
	}

	public void setMessage(Message message) {
		this.message = message;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}