package com.accp.myoa.entity;

/**
 * PositionPopedom generated by MyEclipse Persistence Tools
 */

public class PositionPopedom implements java.io.Serializable {

	// Fields

	private Integer positionPopedomId;
	private Menu menu;
	private DeptPosition deptPosition;
	private Integer menuState;

	// Constructors

	/** default constructor */
	public PositionPopedom() {
	}

	

	// Property accessors

	public Integer getMenuState() {
		return menuState;
	}



	public void setMenuState(Integer menuState) {
		this.menuState = menuState;
	}



	public Integer getPositionPopedomId() {
		return this.positionPopedomId;
	}

	public void setPositionPopedomId(Integer positionPopedomId) {
		this.positionPopedomId = positionPopedomId;
	}

	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	public DeptPosition getDeptPosition() {
		return this.deptPosition;
	}

	public void setDeptPosition(DeptPosition deptPosition) {
		this.deptPosition = deptPosition;
	}

}