package com.accp.myoa.entity;

import java.util.HashSet;
import java.util.Set;

/**
 * ReadState generated by MyEclipse Persistence Tools
 */

public class ReadState implements java.io.Serializable {

	// Fields

	private Integer readStateId;
	private String readStateName;
	private String readStateRemark;
	private Set documentReads = new HashSet(0);
	private Set meetingReads = new HashSet(0);
	private Set bulletinReads = new HashSet(0);

	// Constructors

	/** default constructor */
	public ReadState() {
	}

	/** minimal constructor */
	public ReadState(String readStateName) {
		this.readStateName = readStateName;
	}

	/** full constructor */
	public ReadState(String readStateName, String readStateRemark,
			Set documentReads, Set meetingReads, Set bulletinReads) {
		this.readStateName = readStateName;
		this.readStateRemark = readStateRemark;
		this.documentReads = documentReads;
		this.meetingReads = meetingReads;
		this.bulletinReads = bulletinReads;
	}

	// Property accessors

	public Integer getReadStateId() {
		return this.readStateId;
	}

	public void setReadStateId(Integer readStateId) {
		this.readStateId = readStateId;
	}

	public String getReadStateName() {
		return this.readStateName;
	}

	public void setReadStateName(String readStateName) {
		this.readStateName = readStateName;
	}

	public String getReadStateRemark() {
		return this.readStateRemark;
	}

	public void setReadStateRemark(String readStateRemark) {
		this.readStateRemark = readStateRemark;
	}

	public Set getDocumentReads() {
		return this.documentReads;
	}

	public void setDocumentReads(Set documentReads) {
		this.documentReads = documentReads;
	}

	public Set getMeetingReads() {
		return this.meetingReads;
	}

	public void setMeetingReads(Set meetingReads) {
		this.meetingReads = meetingReads;
	}

	public Set getBulletinReads() {
		return this.bulletinReads;
	}

	public void setBulletinReads(Set bulletinReads) {
		this.bulletinReads = bulletinReads;
	}

}