package com.accp.myoa.entity;

import java.util.Date;

/**
 * Scratchpad generated by MyEclipse Persistence Tools
 */

public class Scratchpad implements java.io.Serializable {

	// Fields

	private Integer scratchpadId;
	private User user;
	private String scratchpadTitle;
	private String scratchpadContent;
	private Date scratchpadDate;

	// Constructors

	/** default constructor */
	public Scratchpad() {
	}

	/** full constructor */
	public Scratchpad(Level level, User user, 
			String scratchpadContent, Date scratchpadDate) {
		
		this.user = user;
		this.scratchpadTitle = scratchpadTitle;
		this.scratchpadContent = scratchpadContent;
		this.scratchpadDate = scratchpadDate;
	}

	// Property accessors

	public Integer getScratchpadId() {
		return this.scratchpadId;
	}

	public void setScratchpadId(Integer scratchpadId) {
		this.scratchpadId = scratchpadId;
	}


	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getScratchpadTitle() {
		return this.scratchpadTitle;
	}

	public void setScratchpadTitle(String scratchpadTitle) {
		this.scratchpadTitle = scratchpadTitle;
	}

	public String getScratchpadContent() {
		return this.scratchpadContent;
	}

	public void setScratchpadContent(String scratchpadContent) {
		this.scratchpadContent = scratchpadContent;
	}

	public Date getScratchpadDate() {
		return this.scratchpadDate;
	}

	public void setScratchpadDate(Date scratchpadDate) {
		this.scratchpadDate = scratchpadDate;
	}

}