package com.accp.myoa.entity;

import java.util.Date;

/**
 * TurnOutForWork generated by MyEclipse Persistence Tools
 */

public class TurnOutForWork implements java.io.Serializable {

	// Fields

	private Integer turnOutForWorkId;
	private User user;
	private Date onDutyDate;
	private Date offDutyDate;

	// Constructors

	/** default constructor */
	public TurnOutForWork() {
	}

	/** full constructor */
	public TurnOutForWork(User user, Date onDutyDate, Date offDutyDate) {
		this.user = user;
		this.onDutyDate = onDutyDate;
		this.offDutyDate = offDutyDate;
	}

	// Property accessors

	public Integer getTurnOutForWorkId() {
		return this.turnOutForWorkId;
	}

	public void setTurnOutForWorkId(Integer turnOutForWorkId) {
		this.turnOutForWorkId = turnOutForWorkId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getOnDutyDate() {
		return this.onDutyDate;
	}

	public void setOnDutyDate(Date onDutyDate) {
		this.onDutyDate = onDutyDate;
	}

	public Date getOffDutyDate() {
		return this.offDutyDate;
	}

	public void setOffDutyDate(Date offDutyDate) {
		this.offDutyDate = offDutyDate;
	}

}