package com.accp.myoa.entity;

/**
 * Unit generated by MyEclipse Persistence Tools
 */

public class Unit implements java.io.Serializable {

	// Fields

	private Integer unitId;
	private String unitName;
	private String unitPhone;
	private String unitFax;
	private String unitPost;
	private String unitAddress;
	private String unitNet;
	private String unitEmail;
	private String unitBank;
	private String nuitBankNo;

	// Constructors

	/** default constructor */
	public Unit() {
	}

	/** minimal constructor */
	public Unit(String unitName, String unitPhone, String unitFax,
			String unitPost, String unitAddress, String unitEmail) {
		this.unitName = unitName;
		this.unitPhone = unitPhone;
		this.unitFax = unitFax;
		this.unitPost = unitPost;
		this.unitAddress = unitAddress;
		this.unitEmail = unitEmail;
	}

	/** full constructor */
	public Unit(String unitName, String unitPhone, String unitFax,
			String unitPost, String unitAddress, String unitNet,
			String unitEmail, String unitBank, String nuitBankNo) {
		this.unitName = unitName;
		this.unitPhone = unitPhone;
		this.unitFax = unitFax;
		this.unitPost = unitPost;
		this.unitAddress = unitAddress;
		this.unitNet = unitNet;
		this.unitEmail = unitEmail;
		this.unitBank = unitBank;
		this.nuitBankNo = nuitBankNo;
	}

	// Property accessors

	public Integer getUnitId() {
		return this.unitId;
	}

	public void setUnitId(Integer unitId) {
		this.unitId = unitId;
	}

	public String getUnitName() {
		return this.unitName;
	}

	public void setUnitName(String unitName) {
		this.unitName = unitName;
	}

	public String getUnitPhone() {
		return this.unitPhone;
	}

	public void setUnitPhone(String unitPhone) {
		this.unitPhone = unitPhone;
	}

	public String getUnitFax() {
		return this.unitFax;
	}

	public void setUnitFax(String unitFax) {
		this.unitFax = unitFax;
	}

	public String getUnitPost() {
		return this.unitPost;
	}

	public void setUnitPost(String unitPost) {
		this.unitPost = unitPost;
	}

	public String getUnitAddress() {
		return this.unitAddress;
	}

	public void setUnitAddress(String unitAddress) {
		this.unitAddress = unitAddress;
	}

	public String getUnitNet() {
		return this.unitNet;
	}

	public void setUnitNet(String unitNet) {
		this.unitNet = unitNet;
	}

	public String getUnitEmail() {
		return this.unitEmail;
	}

	public void setUnitEmail(String unitEmail) {
		this.unitEmail = unitEmail;
	}

	public String getUnitBank() {
		return this.unitBank;
	}

	public void setUnitBank(String unitBank) {
		this.unitBank = unitBank;
	}

	public String getNuitBankNo() {
		return this.nuitBankNo;
	}

	public void setNuitBankNo(String nuitBankNo) {
		this.nuitBankNo = nuitBankNo;
	}

}