package com.accp.myoa.entity;

import java.util.HashSet;
import java.util.Set;

/**
 * UserState generated by MyEclipse Persistence Tools
 */

public class UserState implements java.io.Serializable {

	// Fields

	private Integer userStateId;
	private String userStateName;
	private String userStateRemark;
	private Set users = new HashSet(0);

	// Constructors

	/** default constructor */
	public UserState() {
	}

	/** minimal constructor */
	public UserState(String userStateName) {
		this.userStateName = userStateName;
	}

	/** full constructor */
	public UserState(String userStateName, String userStateRemark, Set users) {
		this.userStateName = userStateName;
		this.userStateRemark = userStateRemark;
		this.users = users;
	}

	// Property accessors

	public Integer getUserStateId() {
		return this.userStateId;
	}

	public void setUserStateId(Integer userStateId) {
		this.userStateId = userStateId;
	}

	public String getUserStateName() {
		return this.userStateName;
	}

	public void setUserStateName(String userStateName) {
		this.userStateName = userStateName;
	}

	public String getUserStateRemark() {
		return this.userStateRemark;
	}

	public void setUserStateRemark(String userStateRemark) {
		this.userStateRemark = userStateRemark;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}