package com.accp.myoa.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by MyEclipse Persistence Tools
 */

public class User implements java.io.Serializable {

	// Fields

	private Integer userId;
	private UserState userState;
	private DeptPosition deptPosition;
	private String loginName;
	private String password;
	private String userName;
	private Integer sex;
	private Date birthday;
	private Integer age;
	private String idCard;
	private String address;
	private String mobilePhone;
	private String comPhone;
	private String qq;
	private String fax;
	private String email;
	private String userRemark;
	private Set carAppliesForDebuger = new HashSet(0);
	private Set carAppliesForProposer = new HashSet(0);
	private Set documents = new HashSet(0);
	private Set messageReceives = new HashSet(0);
	private Set turnOutForWorks = new HashSet(0);
	private Set egresses = new HashSet(0);
	private Set weekDiaries = new HashSet(0);
	private Set documentExamines = new HashSet(0);
	private Set scratchpads = new HashSet(0);
	private Set leaveWords = new HashSet(0);
	private Set bulletinExamines = new HashSet(0);
	private Set meetingSummaryScans = new HashSet(0);
	private Set emails = new HashSet(0);
	private Set meetingsForUserId = new HashSet(0);
	private Set meetingsForExaminer = new HashSet(0);
	private Set messages = new HashSet(0);
	private Set bulletinReads = new HashSet(0);
	private Set files = new HashSet(0);
	private Set documentReads = new HashSet(0);
	private Set meetingReads = new HashSet(0);
	private Set egressExamines = new HashSet(0);
	private Set diaries = new HashSet(0);
	private Set emailReceivces = new HashSet(0);
	private Set carAppliesForMotorMan = new HashSet(0);
	private Set bulletins = new HashSet(0);

	// Constructors

	/** default constructor */
	public User() {
	}

	/** minimal constructor */
	public User(UserState userState, DeptPosition deptPosition,
			String loginName, String password, String userName, Integer sex,
			Date birthday, Integer age, String idCard) {
		this.userState = userState;
		this.deptPosition = deptPosition;
		this.loginName = loginName;
		this.password = password;
		this.userName = userName;
		this.sex = sex;
		this.birthday = birthday;
		this.age = age;
		this.idCard = idCard;
	}

	/** full constructor */
	public User(UserState userState, DeptPosition deptPosition,
			String loginName, String password, String userName, Integer sex,
			Date birthday, Integer age, String idCard, String address,
			String mobilePhone, String comPhone, String qq, String fax,
			String email, String userRemark, Set carAppliesForDebuger,
			Set carAppliesForProposer, Set documents, Set messageReceives,
			Set turnOutForWorks, Set egresses, Set weekDiaries,
			Set documentExamines, Set scratchpads, Set leaveWords,
			Set bulletinExamines, Set meetingSummaryScans, Set emails,
			Set meetingsForUserId, Set meetingsForExaminer, Set messages,
			Set bulletinReads, Set files, Set documentReads, Set meetingReads,
			Set egressExamines, Set diaries, Set emailReceivces,
			Set carAppliesForMotorMan, Set bulletins) {
		this.userState = userState;
		this.deptPosition = deptPosition;
		this.loginName = loginName;
		this.password = password;
		this.userName = userName;
		this.sex = sex;
		this.birthday = birthday;
		this.age = age;
		this.idCard = idCard;
		this.address = address;
		this.mobilePhone = mobilePhone;
		this.comPhone = comPhone;
		this.qq = qq;
		this.fax = fax;
		this.email = email;
		this.userRemark = userRemark;
		this.carAppliesForDebuger = carAppliesForDebuger;
		this.carAppliesForProposer = carAppliesForProposer;
		this.documents = documents;
		this.messageReceives = messageReceives;
		this.turnOutForWorks = turnOutForWorks;
		this.egresses = egresses;
		this.weekDiaries = weekDiaries;
		this.documentExamines = documentExamines;
		this.scratchpads = scratchpads;
		this.leaveWords = leaveWords;
		this.bulletinExamines = bulletinExamines;
		this.meetingSummaryScans = meetingSummaryScans;
		this.emails = emails;
		this.meetingsForUserId = meetingsForUserId;
		this.meetingsForExaminer = meetingsForExaminer;
		this.messages = messages;
		this.bulletinReads = bulletinReads;
		this.files = files;
		this.documentReads = documentReads;
		this.meetingReads = meetingReads;
		this.egressExamines = egressExamines;
		this.diaries = diaries;
		this.emailReceivces = emailReceivces;
		this.carAppliesForMotorMan = carAppliesForMotorMan;
		this.bulletins = bulletins;
	}

	// Property accessors

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public UserState getUserState() {
		return this.userState;
	}

	public void setUserState(UserState userState) {
		this.userState = userState;
	}

	public DeptPosition getDeptPosition() {
		return this.deptPosition;
	}

	public void setDeptPosition(DeptPosition deptPosition) {
		this.deptPosition = deptPosition;
	}

	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getIdCard() {
		return this.idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getMobilePhone() {
		return this.mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	public String getComPhone() {
		return this.comPhone;
	}

	public void setComPhone(String comPhone) {
		this.comPhone = comPhone;
	}

	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUserRemark() {
		return this.userRemark;
	}

	public void setUserRemark(String userRemark) {
		this.userRemark = userRemark;
	}

	public Set getCarAppliesForDebuger() {
		return this.carAppliesForDebuger;
	}

	public void setCarAppliesForDebuger(Set carAppliesForDebuger) {
		this.carAppliesForDebuger = carAppliesForDebuger;
	}

	public Set getCarAppliesForProposer() {
		return this.carAppliesForProposer;
	}

	public void setCarAppliesForProposer(Set carAppliesForProposer) {
		this.carAppliesForProposer = carAppliesForProposer;
	}

	public Set getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set documents) {
		this.documents = documents;
	}

	public Set getMessageReceives() {
		return this.messageReceives;
	}

	public void setMessageReceives(Set messageReceives) {
		this.messageReceives = messageReceives;
	}

	public Set getTurnOutForWorks() {
		return this.turnOutForWorks;
	}

	public void setTurnOutForWorks(Set turnOutForWorks) {
		this.turnOutForWorks = turnOutForWorks;
	}

	public Set getEgresses() {
		return this.egresses;
	}

	public void setEgresses(Set egresses) {
		this.egresses = egresses;
	}

	public Set getWeekDiaries() {
		return this.weekDiaries;
	}

	public void setWeekDiaries(Set weekDiaries) {
		this.weekDiaries = weekDiaries;
	}

	public Set getDocumentExamines() {
		return this.documentExamines;
	}

	public void setDocumentExamines(Set documentExamines) {
		this.documentExamines = documentExamines;
	}

	public Set getScratchpads() {
		return this.scratchpads;
	}

	public void setScratchpads(Set scratchpads) {
		this.scratchpads = scratchpads;
	}

	public Set getLeaveWords() {
		return this.leaveWords;
	}

	public void setLeaveWords(Set leaveWords) {
		this.leaveWords = leaveWords;
	}

	public Set getBulletinExamines() {
		return this.bulletinExamines;
	}

	public void setBulletinExamines(Set bulletinExamines) {
		this.bulletinExamines = bulletinExamines;
	}

	public Set getMeetingSummaryScans() {
		return this.meetingSummaryScans;
	}

	public void setMeetingSummaryScans(Set meetingSummaryScans) {
		this.meetingSummaryScans = meetingSummaryScans;
	}

	public Set getEmails() {
		return this.emails;
	}

	public void setEmails(Set emails) {
		this.emails = emails;
	}

	public Set getMeetingsForUserId() {
		return this.meetingsForUserId;
	}

	public void setMeetingsForUserId(Set meetingsForUserId) {
		this.meetingsForUserId = meetingsForUserId;
	}

	public Set getMeetingsForExaminer() {
		return this.meetingsForExaminer;
	}

	public void setMeetingsForExaminer(Set meetingsForExaminer) {
		this.meetingsForExaminer = meetingsForExaminer;
	}

	public Set getMessages() {
		return this.messages;
	}

	public void setMessages(Set messages) {
		this.messages = messages;
	}

	public Set getBulletinReads() {
		return this.bulletinReads;
	}

	public void setBulletinReads(Set bulletinReads) {
		this.bulletinReads = bulletinReads;
	}

	public Set getFiles() {
		return this.files;
	}

	public void setFiles(Set files) {
		this.files = files;
	}

	public Set getDocumentReads() {
		return this.documentReads;
	}

	public void setDocumentReads(Set documentReads) {
		this.documentReads = documentReads;
	}

	public Set getMeetingReads() {
		return this.meetingReads;
	}

	public void setMeetingReads(Set meetingReads) {
		this.meetingReads = meetingReads;
	}

	public Set getEgressExamines() {
		return this.egressExamines;
	}

	public void setEgressExamines(Set egressExamines) {
		this.egressExamines = egressExamines;
	}

	public Set getDiaries() {
		return this.diaries;
	}

	public void setDiaries(Set diaries) {
		this.diaries = diaries;
	}

	public Set getEmailReceivces() {
		return this.emailReceivces;
	}

	public void setEmailReceivces(Set emailReceivces) {
		this.emailReceivces = emailReceivces;
	}

	public Set getCarAppliesForMotorMan() {
		return this.carAppliesForMotorMan;
	}

	public void setCarAppliesForMotorMan(Set carAppliesForMotorMan) {
		this.carAppliesForMotorMan = carAppliesForMotorMan;
	}

	public Set getBulletins() {
		return this.bulletins;
	}

	public void setBulletins(Set bulletins) {
		this.bulletins = bulletins;
	}

}