package com.accp.myoa.entity;

import java.util.Date;

/**
 * WeekDiary generated by MyEclipse Persistence Tools
 */

public class WeekDiary implements java.io.Serializable {

	// Fields

	private Integer weekDiaryId;
	private ComleteDegress comleteDegress;
	private User user;
	private String weekDiaryTitle;
	private String weekDiaryContent;
	private Date weekDiaryDate;

	// Constructors

	/** default constructor */
	public WeekDiary() {
	}

	/** full constructor */
	public WeekDiary(ComleteDegress comleteDegress, User user,
			String weekDiaryTitle, String weekDiaryContent, Date weekDiaryDate) {
		this.comleteDegress = comleteDegress;
		this.user = user;
		this.weekDiaryTitle = weekDiaryTitle;
		this.weekDiaryContent = weekDiaryContent;
		this.weekDiaryDate = weekDiaryDate;
	}

	// Property accessors

	public Integer getWeekDiaryId() {
		return this.weekDiaryId;
	}

	public void setWeekDiaryId(Integer weekDiaryId) {
		this.weekDiaryId = weekDiaryId;
	}

	public ComleteDegress getComleteDegress() {
		return this.comleteDegress;
	}

	public void setComleteDegress(ComleteDegress comleteDegress) {
		this.comleteDegress = comleteDegress;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getWeekDiaryTitle() {
		return this.weekDiaryTitle;
	}

	public void setWeekDiaryTitle(String weekDiaryTitle) {
		this.weekDiaryTitle = weekDiaryTitle;
	}

	public String getWeekDiaryContent() {
		return this.weekDiaryContent;
	}

	public void setWeekDiaryContent(String weekDiaryContent) {
		this.weekDiaryContent = weekDiaryContent;
	}

	public Date getWeekDiaryDate() {
		return this.weekDiaryDate;
	}

	public void setWeekDiaryDate(Date weekDiaryDate) {
		this.weekDiaryDate = weekDiaryDate;
	}

}