/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.accp.myoa.web.action;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.accp.myoa.entity.User;
import com.accp.myoa.service.MenuService;
import com.accp.myoa.service.UserService;
import com.accp.myoa.web.form.UserForm;
import com.accp.myoa.common.OnLineCount;

public class LoginAction extends DispatchAction {
	private UserService userService;
	private MenuService menuService;

	public void setMenuService(MenuService menuService) {
		this.menuService = menuService;
	}


	public void setUserService(UserService userService) {
		this.userService = userService;
	}


	public ActionForward doLogin(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws ServletException {
		UserForm userForm=(UserForm)form;
		User user=userForm.getUser();
		User reUser=userService.getByNameAndPwd(user);
		if(reUser==null){
			request.setAttribute("before", user);
			request.setAttribute("info", "用户名或密码错误!");
			return mapping.findForward("login");
		}else{
			HttpSession session=request.getSession();
			session.setAttribute("user", reUser);
			int count=OnLineCount.getCount();
			count++;
			OnLineCount.setCount(count);
			return mapping.findForward("index");
		}
		
	}
	
	public ActionForward doExit(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HttpSession session=request.getSession();
		session.invalidate();
		return mapping.findForward("login");
		
	}
	
	public ActionForward toIndex(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		return mapping.findForward("index");
		
	}
	
	
}